name: Unit Tests
on:
  workflow_call:

permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.13']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            .github/workflows/requirements/unit-tests.txt

      - name: Install Python dependencies
        run: |
          pip install .
          pip install -r .github/workflows/requirements/unit-tests.txt

      - name: Run Unit Tests (coverage on 3.13)
        run: |
          python3 -m build  # build package for compatibility with publish.yml
          if [ "${{ matrix.python-version }}" = "3.13" ]; then
            # run unit tests with coverage for 3.13
            coverage run -m pytest
            coverage json -o pr_coverage.json
          else
            # other matrix versions just run tests
            python3 -m pytest
          fi

      - name: Upload coverage artifact
        # this is needed so we can compare diffs in coverage.yml
        if: ${{ matrix.python-version == '3.13' }}
        uses: actions/upload-artifact@v6
        with:
          name: pr-coverage-${{ github.sha }}
          path: pr_coverage.json
